/// LED animation engine for the Neopixel ring.
///
/// # Built-in animations
///
/// | Name       | Description                                               |
/// |------------|-----------------------------------------------------------|
/// | `solid`    | All LEDs show a single static colour (default)            |
/// | `rainbow`  | A rotating rainbow hue-wheel across all LEDs              |
/// | `spinning` | A single bright pixel (with fading tail) circles the ring |
/// | `breathe`  | All LEDs fade in and out using the current colour         |
/// | `custom`   | User-supplied frame animation baked in at compile time    |
///
/// # Custom animation via `animation.png`
///
/// Drop an image called `animation.png` next to `Cargo.toml` before building:
///
/// - **Width**  = `LED_COUNT` pixels — one pixel per LED per frame
/// - **Height** = number of animation frames
/// - **Format** = 8-bit RGB or RGBA (alpha channel is ignored)
///
/// Each row in the image is one frame; rows play top-to-bottom and loop.
/// Rebuild and reflash the firmware after adding or changing the file.
///
/// The `custom` effect appears in the HomeAssistant effect dropdown only when
/// `animation.png` was present at the last build.
///
/// # Animation speeds
///
/// All timing constants live in `src/config.rs` so non-technical users only
/// need to edit one file.  The main loop ticks at ~20 Hz (50 ms sleep), so
/// one "tick" ≈ 50 ms.

use smart_leds::RGB8;

use crate::config::{
    LED_COUNT, ANIM_RAINBOW_SPEED, ANIM_SPINNING_TICKS_PER_PIXEL, ANIM_BREATHE_SPEED,
    ANIM_CUSTOM_TICKS_PER_FRAME,
};

// Generated by build.rs from animation.png (if present in the project root).
// Defines:
//   pub const CUSTOM_ANIMATION_FRAMES: &[u8]     — packed RGB bytes, row-major
//   pub const CUSTOM_ANIMATION_FRAME_COUNT: usize — number of rows (frames)
//   pub const CUSTOM_ANIMATION_FRAME_LEDS: usize  — number of columns (LEDs per frame)
include!(concat!(env!("OUT_DIR"), "/custom_anim.rs"));

// Compile-time guard: frame count must either be zero, or the PNG width must match the
// configured LED count.
const _: () = assert!(
    CUSTOM_ANIMATION_FRAME_COUNT == 0 || CUSTOM_ANIMATION_FRAME_LEDS == LED_COUNT,
    "animation.png width must equal LED_COUNT (src/config.rs). \
     Resize the image so that each row has exactly LED_COUNT pixels.",
);

// ── Animation type ────────────────────────────────────────────────────────────

/// Selects the active LED animation.
///
/// The variant names map 1:1 to HomeAssistant effect strings so the HA UI can
/// switch animations without extra conversion logic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum AnimationType {
    /// Static colour — identical to the pre-animation behaviour. (default)
    #[default]
    Solid,
    /// Rotating rainbow hue-wheel.
    Rainbow,
    /// Single bright pixel circling the ring with a short fading tail.
    Spinning,
    /// Whole ring fades in and out using the current colour.
    Breathe,
    /// User-supplied frame animation baked in from `animation.png`.
    Custom,
}

impl AnimationType {
    /// Construct from the HA effect name string sent over MQTT.
    ///
    /// Unknown names fall back to [`AnimationType::Solid`].
    pub fn from_effect_name(name: &str) -> Self {
        Self::from_effect_name_with_custom(name, CUSTOM_ANIMATION_FRAME_COUNT > 0)
    }

    /// Construct from an HA effect name with explicit custom-animation support.
    ///
    /// This allows tests to validate behavior deterministically regardless of
    /// whether `animation.png` was present at build time.
    fn from_effect_name_with_custom(name: &str, has_custom: bool) -> Self {
        match name {
            "rainbow" => Self::Rainbow,
            "spinning" => Self::Spinning,
            "breathe" => Self::Breathe,
            "custom" if has_custom => Self::Custom,
            _ => Self::Solid,
        }
    }

    /// The HA effect name string for this variant.
    pub fn as_effect_name(self) -> &'static str {
        match self {
            Self::Solid => "solid",
            Self::Rainbow => "rainbow",
            Self::Spinning => "spinning",
            Self::Breathe => "breathe",
            Self::Custom => "custom",
        }
    }

    /// Slice of all effect names advertised to HomeAssistant.
    ///
    /// `"custom"` is only included when `animation.png` was present at the
    /// last build (i.e. `CUSTOM_ANIMATION_FRAME_COUNT > 0`).
    pub fn effect_list() -> &'static [&'static str] {
        Self::effect_list_with_custom(CUSTOM_ANIMATION_FRAME_COUNT > 0)
    }

    /// Effect list with explicit custom-animation support.
    ///
    /// This allows tests to cover both branches without relying on generated
    /// constants from `build.rs`.
    fn effect_list_with_custom(has_custom: bool) -> &'static [&'static str] {
        const EFFECTS_BASE: &[&str] = &["solid", "rainbow", "spinning", "breathe"];
        const EFFECTS_WITH_CUSTOM: &[&str] =
            &["solid", "rainbow", "spinning", "breathe", "custom"];

        if has_custom {
            EFFECTS_WITH_CUSTOM
        } else {
            EFFECTS_BASE
        }
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Compute the pixel array for one animation frame.
///
/// * `r`, `g`, `b`    — base colour from [`LightState`]
/// * `brightness`     — master brightness (0-255) from [`LightState`]
/// * `on`             — if `false`, returns all-off regardless of animation
/// * `anim`           — which animation to render
/// * `phase`          — monotonically-increasing tick counter from [`LedController`]
///
/// [`LightState`]: crate::led::LightState
/// [`LedController`]: crate::led::LedController
pub fn compute_frame(
    r: u8,
    g: u8,
    b: u8,
    brightness: u8,
    on: bool,
    anim: AnimationType,
    phase: u32,
) -> [RGB8; LED_COUNT] {
    if !on {
        return [RGB8::new(0, 0, 0); LED_COUNT];
    }

    match anim {
        AnimationType::Solid => solid(r, g, b, brightness),
        AnimationType::Rainbow => rainbow(phase, brightness),
        AnimationType::Spinning => spinning(r, g, b, brightness, phase),
        AnimationType::Breathe => breathe(r, g, b, brightness, phase),
        AnimationType::Custom => {
            if CUSTOM_ANIMATION_FRAME_COUNT == 0 {
                solid(r, g, b, brightness)
            } else {
                custom_frame(brightness, phase)
            }
        }
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Scale an 8-bit colour channel by a 0-255 brightness factor.
#[inline]
fn scale(channel: u8, brightness: u8) -> u8 {
    ((channel as u16 * brightness as u16) / 255) as u8
}

/// Convert a 0-255 hue (full saturation and value) to an RGB8 colour.
///
/// Uses a six-sector approximation; no floating-point required.
fn hsv_hue_to_rgb(hue: u8) -> RGB8 {
    let h = hue as u16 * 6;
    let sector = h / 256;        // 0-5
    let frac = (h % 256) as u8;  // 0-255 fractional part within the sector
    let (r, g, b) = match sector {
        0 => (255u8, frac,       0),
        1 => (255 - frac, 255,   0),
        2 => (0,    255,         frac),
        3 => (0,    255 - frac,  255),
        4 => (frac, 0,           255),
        _ => (255,  0,           255 - frac),
    };
    RGB8::new(r, g, b)
}

// ── Animation implementations ─────────────────────────────────────────────────

/// All LEDs set to the same static colour.
fn solid(r: u8, g: u8, b: u8, brightness: u8) -> [RGB8; LED_COUNT] {
    let c = RGB8::new(scale(r, brightness), scale(g, brightness), scale(b, brightness));
    [c; LED_COUNT]
}

/// Rotating rainbow hue-wheel.
///
/// Each LED is assigned a different hue, evenly spaced around the colour
/// circle.  The whole pattern rotates by advancing the hue offset each tick.
fn rainbow(phase: u32, brightness: u8) -> [RGB8; LED_COUNT] {
    let mut pixels = [RGB8::new(0, 0, 0); LED_COUNT];
    // Advance hue by ANIM_RAINBOW_SPEED steps per tick.
    let offset = phase.wrapping_mul(ANIM_RAINBOW_SPEED) as u8;
    for i in 0..LED_COUNT {
        let hue = offset.wrapping_add((i as u16 * 256 / LED_COUNT as u16) as u8);
        let c = hsv_hue_to_rgb(hue);
        pixels[i] = RGB8::new(scale(c.r, brightness), scale(c.g, brightness), scale(c.b, brightness));
    }
    pixels
}

/// Single bright pixel circling the ring with a 3-pixel decaying tail.
fn spinning(r: u8, g: u8, b: u8, brightness: u8, phase: u32) -> [RGB8; LED_COUNT] {
    let mut pixels = [RGB8::new(0, 0, 0); LED_COUNT];
    // Move the head one position forward every ANIM_SPINNING_TICKS_PER_PIXEL ticks.
    let head = (phase as usize / ANIM_SPINNING_TICKS_PER_PIXEL as usize) % LED_COUNT;
    for i in 0..LED_COUNT {
        // Distance behind the head (wrap-around safe).
        let dist = (LED_COUNT + head - i) % LED_COUNT;
        let tail_brightness: u8 = match dist {
            0 => brightness,           // head pixel — full brightness
            1 => brightness / 4,       // 1 step behind
            2 => brightness / 12,      // 2 steps behind
            _ => 0,
        };
        if tail_brightness > 0 {
            pixels[i] = RGB8::new(
                scale(r, tail_brightness),
                scale(g, tail_brightness),
                scale(b, tail_brightness),
            );
        }
    }
    pixels
}

/// All LEDs breathe (fade in and out) using the current colour.
///
/// Uses a triangle wave oscillating over a 256-tick period
/// (scaled by `ANIM_BREATHE_SPEED`).
fn breathe(r: u8, g: u8, b: u8, max_brightness: u8, phase: u32) -> [RGB8; LED_COUNT] {
    let t = (phase.wrapping_mul(ANIM_BREATHE_SPEED) & 0xFF) as u8;
    // Triangle wave: 0→255→0 over 256 ticks.
    let factor: u8 = if t < 128 {
        t.saturating_mul(2)
    } else {
        (255u8).saturating_sub(t.saturating_sub(128).saturating_mul(2))
    };
    solid(r, g, b, scale(max_brightness, factor))
}

/// Play one frame from the baked-in custom animation data.
fn custom_frame(brightness: u8, phase: u32) -> [RGB8; LED_COUNT] {
    custom_frame_from_data(
        brightness,
        phase,
        CUSTOM_ANIMATION_FRAMES,
        CUSTOM_ANIMATION_FRAME_COUNT,
        ANIM_CUSTOM_TICKS_PER_FRAME,
    )
}

/// Render a custom-animation frame from caller-provided data.
///
/// This helper exists so tests can exercise both "no frames" and
/// "frames present" paths deterministically without depending on build-script
/// generated constants from `animation.png`.
fn custom_frame_from_data(
    brightness: u8,
    phase: u32,
    frames: &[u8],
    frame_count: usize,
    ticks_per_frame: u32,
) -> [RGB8; LED_COUNT] {
    if frame_count == 0 || ticks_per_frame == 0 {
        // Fixes bug #7 — if there are no frames, return all-off instead of panicking on divide by zero.
        return [RGB8::new(0, 0, 0); LED_COUNT];
    }

    let frame_stride = LED_COUNT * 3;
    if frames.len() < frame_count.saturating_mul(frame_stride) {
        return [RGB8::new(0, 0, 0); LED_COUNT];
    }

    let frame_idx = (phase as usize / ticks_per_frame as usize) % frame_count;
    let frame_start = frame_idx * LED_COUNT * 3;
    let frame = &frames[frame_start..frame_start + LED_COUNT * 3];

    let mut pixels = [RGB8::new(0, 0, 0); LED_COUNT];
    for i in 0..LED_COUNT {
        pixels[i] = RGB8::new(
            scale(frame[i * 3],     brightness),
            scale(frame[i * 3 + 1], brightness),
            scale(frame[i * 3 + 2], brightness),
        );
    }
    pixels
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_effect_name_custom_maps_to_solid_when_custom_is_unavailable() {
        let effect = AnimationType::from_effect_name_with_custom("custom", false);
        assert_eq!(effect, AnimationType::Solid);
    }

    #[test]
    fn from_effect_name_custom_maps_to_custom_when_custom_is_available() {
        let effect = AnimationType::from_effect_name_with_custom("custom", true);
        assert_eq!(effect, AnimationType::Custom);
    }

    #[test]
    fn effect_list_excludes_custom_when_unavailable() {
        let effects = AnimationType::effect_list_with_custom(false);
        assert_eq!(effects, &["solid", "rainbow", "spinning", "breathe"]);
    }

    #[test]
    fn effect_list_includes_custom_when_available() {
        let effects = AnimationType::effect_list_with_custom(true);
        assert_eq!(
            effects,
            &["solid", "rainbow", "spinning", "breathe", "custom"]
        );
    }

    #[test]
    fn custom_frame_returns_off_when_no_frames() {
        let result = custom_frame_from_data(255, 0, &[], 0, 1);
        assert_eq!(result, [RGB8::new(0, 0, 0); LED_COUNT]);
    }

    #[test]
    fn custom_frame_renders_injected_frame_data() {
        let mut frames = vec![0u8; LED_COUNT * 3 * 2];

        // Frame 0, LED 0 -> (100, 10, 1)
        frames[0] = 100;
        frames[1] = 10;
        frames[2] = 1;

        // Frame 1, LED 0 -> (0, 50, 5)
        let frame1 = LED_COUNT * 3;
        frames[frame1] = 0;
        frames[frame1 + 1] = 50;
        frames[frame1 + 2] = 5;

        let result0 = custom_frame_from_data(255, 0, &frames, 2, 1);
        let result1 = custom_frame_from_data(255, 1, &frames, 2, 1);

        assert_eq!(result0[0], RGB8::new(100, 10, 1));
        assert_eq!(result1[0], RGB8::new(0, 50, 5));
    }

    #[test]
    fn custom_frame_returns_off_when_ticks_per_frame_is_zero() {
        let frames = vec![255u8; LED_COUNT * 3];
        let result = custom_frame_from_data(255, 0, &frames, 1, 0);
        assert_eq!(result, [RGB8::new(0, 0, 0); LED_COUNT]);
    }
}
